// // Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

// import (
// 	gin "github.com/gin-gonic/gin"

// 	mock "github.com/stretchr/testify/mock"
// )

// // AuthClient is an autogenerated mock type for the AuthClient type
// type AuthClient struct {
// 	mock.Mock
// }

// // AuthUser provides a mock function with given fields:
// func (_m *AuthClient) AuthUser() gin.HandlerFunc {
// 	ret := _m.Called()

// 	var r0 gin.HandlerFunc
// 	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
// 		r0 = rf()
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).(gin.HandlerFunc)
// 		}
// 	}

// 	return r0
// }
