name: Build Docker images

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Execute tests]
    branches: [main]
    types: [completed]

jobs:
  admin-ui:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./cns/admin/emeris-admin
          tags: gcr.io/tendermint-dev/emeris-admin-ui:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-admin-ui:${{ github.sha }}

  cns-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: gcr.io/tendermint-dev/emeris-cns-server:${{ steps.get_version.outputs.version-without-v }},gcr.io/tendermint-dev/emeris-cns-server:${{ github.sha }}
          build-args: |
            GIT_TOKEN=${{ secrets.TENDERBOT_GIT_TOKEN }}

  deploy-on-dev:
    runs-on: self-hosted
    needs: cns-server

    steps:
      - name: Call repository_dispatch on demeris-backend
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: allinbits/demeris-backend
          event-type: dev-push-cns-server
          client-payload: '{"repo_name":"emeris-cns-server","branch_name":"main","image_name":"emeris-cns-server","image_sha":"${{ github.sha }}","service_name":"cns-server"}'
